name: dartafis
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/karlaycosta/dartafis

topics:
  - fingerprint
  - afis
  - matcher

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
