name: dartafis
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/karlaycosta/dartafis

topics:
  - fingerprint
  - afis
  - matcher

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0
