name: dartafis
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/karlaycosta/dartafis

topics:
  - fingerprint
  - afis
  - matcher

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
  # very_good_analysis: ^6.0.0
